version: '2'

services:
    service_wd_beanstalk:
        image:
            coomy/beanstalk:1.10
        container_name:
            wd_queue
        restart:
            always
        networks:
            - wd_network

    service_wd_mysql:
        image:
            mysql
        container_name:
            wd_mysql
        restart:
            always
        networks:
            - wd_network
        environment:
            - MYSQL_DATABASE=wd
            - MYSQL_ROOT_PASSWORD=rootpass
            - MYSQL_USER=wd
            - MYSQL_PASSWORD=wdpass
        ports:
            3306:3306
        volumes:
            - mysql:/var/lib/mysql

    service_wd_php:
        image:
            coomy/php:5.6-fpm
        container_name:
            wd_php
        restart:
            always
        depends_on:
            - service_wd_mysql
            - service_wd_beanstalk
        environment:
            - DB_HOST=wd_mysql
            - BEANSTALKD_HOST=wd_queue
        networks:
            - wd_network
        volumes:
            - php:/var/project
        working_dir:
            - /var/project

    service_wd_nginx:
        image:
            nginx
        container_name:
            wd_nginx
        restart:
            always
        networks:
            - wd_network
        volumes:
            - php:/var/project 
            - nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"

networks:
    wd_network:
        driver:
            bridge

