version: '2'

services:
    nginx_php:
        image:
            coomy/nginx:php5.5.9
        container_name:
            wd_nginx_php
        hostname:
            nginx-php5
        restart:
            always
        networks:
            - wd_network
        stdin_open:
            true
        tty:
            true
        volumes:
            - ~/Docker/code:/usr/share/nginx/html/
            - ~/Docker/log:/var/log/nginx
        command:
            bash
        ports:
            - "80:80"
        working_dir:
            /usr/share/nginx/html/

    service_wd_mysql:
        image:
            mysql:latest
        container_name:
            wd_mysql
        hostname:
            mysql
        restart:
            always
        networks:
            - wd_network
        environment:
            - MYSQL_DATABASE=wd
            - MYSQL_ROOT_PASSWORD=rootpass
            - MYSQL_USER=wd
            - MYSQL_PASSWORD=wdpass
        ports:
            - 3306:3306
        command:
            mysqld

    service_node:
        image:
            coomy/develop:node
        container_name:
            wd_dev_node
        hostname:
            dev_node
        restart:
            always

        environment:
            - NODE_PACKAGE="gulp bower"
        networks:
            - wd_network
        volumes:
            - ~/Docker/code:$HOME/code
        ports:
            - "33:22"
            - "3000:3000"
        command:
            /bin/bash
            /home/ubuntu/start/run.bash

    service_phpmyadmin:
        image:
            phpmyadmin/phpmyadmin:latest
        container_name:
            wd_phpMyAdmin

        restart:
            always

        networks:
            - wd_network
        links:
            - service_wd_mysql:pma_db
        environment:
            - PMA_HOST=mysql
        ports:
            - "8080:80"

networks:
    wd_network:
        driver:
            bridge
